package:
  name: hjson
  version: "1.5.2"

source:
  fn: hjson-1.5.2.zip
  url: https://pypi.python.org/packages/source/h/hjson/hjson-1.5.2.zip
  md5: 95767b433d37d89a53587fcd7d2b4e38
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - hjson = hjson:main
    #
    # Would create an entry point called hjson that calls hjson.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - hjson
    - hjson.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/laktak/hjson-py
  license: MIT License or Academic Free License (AFL)
  summary: 'JSON for Humans, allows comments and is less error prone.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
